return {}
-- return {
--   "ojroques/nvim-osc52",
--   config = function()
--     local osc52 = require("osc52")
--     osc52.setup({
--       max_length = 0,         -- unlimited length
--       silent = false,         -- echo copy success
--       trim = false,
--     })
--
--     -- Use <leader>y to copy visually selected text to system clipboard
--     vim.keymap.set("v", "<leader>y", osc52.copy_visual, { desc = "Copy to clipboard (OSC52)" })
--
--     -- Or automatically override the default yank to always use OSC52
--     vim.api.nvim_create_autocmd("TextYankPost", {
--       callback = function()
--         if vim.v.event.operator == "y" and vim.v.event.regname == "" then
--           osc52.copy_register("")
--         end
--       end,
--     })
--   end,
-- }
